model {
  file: "model.sdf"
  file_format {
    version {
      major: 1
      minor: 6
    }
    name: "sdf"
  }
}
name: "Urban Service Room Straight"
description: "Service room with 2 entry points."
authors {
  name: "Cole Biesemeyer"
  email: "cole@openrobotics.org"
}
dependencies {
  uri: "https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/Urban Platform"
}

